"""Query-time embedding for the existing BAAI/bge-m3 Qdrant collection.

Production (default): Qdrant Cloud Inference — no local model weights.
Development opt-in: local SentenceTransformer via EMBEDDING_PROVIDER=local.

The collection was ingested with BAAI/bge-m3 (1024-dim, cosine, normalized).
"""

from __future__ import annotations

import logging
from typing import Any

from qdrant_client.http import models as qm

from app.config import get_settings

# Must match ingest_policies.py / collection configuration.
DEFAULT_EMBEDDING_MODEL = "BAAI/bge-m3"
DEFAULT_QDRANT_INFERENCE_MODEL = "bge-m3"
VECTOR_SIZE = 1024

logger = logging.getLogger(__name__)

_model: Any | None = None
_model_name: str | None = None


class EmbeddingError(RuntimeError):
    """Raised when query embedding fails."""


def get_embedding_provider() -> str:
    return get_settings().embedding_provider.strip().lower()


def get_embedding_model_name() -> str:
    return get_settings().rag_embedding_model


def get_qdrant_inference_model() -> str:
    return get_settings().qdrant_inference_model


def uses_qdrant_cloud_inference() -> bool:
    return get_embedding_provider() == "qdrant"


def build_search_query(query: str) -> list[float] | qm.Document:
    """Return the Qdrant query input for the configured embedding provider."""
    text = (query or "").strip()
    if not text:
        raise ValueError("query must be a non-empty string")

    if uses_qdrant_cloud_inference():
        model = get_qdrant_inference_model()
        logger.debug("Using Qdrant Cloud Inference model=%s", model)
        return qm.Document(text=text, model=model)

    vector = _embed_query_local(text)
    if len(vector) != VECTOR_SIZE:
        raise EmbeddingError(
            f"Unexpected embedding size {len(vector)}; expected {VECTOR_SIZE} "
            f"for {get_embedding_model_name()}"
        )
    return vector


def embed_query(query: str) -> list[float]:
    """Encode a query to a dense vector (local provider only).

    For the default Qdrant Cloud Inference provider, use ``build_search_query``
    which returns a ``Document`` handled server-side by Qdrant.
    """
    if uses_qdrant_cloud_inference():
        raise EmbeddingError(
            "embed_query() is not available with EMBEDDING_PROVIDER=qdrant. "
            "Query embeddings are generated by Qdrant Cloud Inference."
        )
    return _embed_query_local(query)


def _embed_query_local(query: str) -> list[float]:
    text = (query or "").strip()
    if not text:
        raise ValueError("query must be a non-empty string")

    model = _get_local_embedding_model()
    vector = model.encode(
        text,
        normalize_embeddings=True,
        show_progress_bar=False,
    )
    return vector.tolist()


def _create_local_model(model_name: str) -> Any:
    try:
        from sentence_transformers import SentenceTransformer
    except ImportError as exc:  # pragma: no cover
        raise EmbeddingError(
            "EMBEDDING_PROVIDER=local requires sentence-transformers and torch. "
            "Install them or set EMBEDDING_PROVIDER=qdrant."
        ) from exc

    try:
        return SentenceTransformer(model_name, local_files_only=True)
    except Exception:
        logger.info(
            "Embedding model %s not fully cached locally; loading from Hugging Face Hub once",
            model_name,
        )
        return SentenceTransformer(model_name)


def _get_local_embedding_model() -> Any:
    """Return the process-wide local model (opt-in dev/test only)."""
    global _model, _model_name
    name = get_embedding_model_name()
    if _model is not None and _model_name == name:
        return _model
    logger.info("Loading local embedding model: %s", name)
    _model = _create_local_model(name)
    _model_name = name
    return _model


def warm_embedding_model() -> None:
    """Eager-load local weights — only when EMBEDDING_PROVIDER=local."""
    if not uses_qdrant_cloud_inference():
        _get_local_embedding_model()


def reset_embedding_model() -> None:
    """Drop cached local model (tests / shutdown)."""
    global _model, _model_name
    _model = None
    _model_name = None
